import image1 from "../asset/images/slide1.jpg";
import image2 from "../asset/images/slide2.jpg";
import image3 from "../asset/images/slide3.jpg";
import image4 from "../asset/images/slide4.jpg";
import image5 from "../asset/images/slide5.jpg";

export default [
  {
    id: 1,
    img: image1,
    title: "White Car",
    desc: "A White Car",
    price: 250000,
    distance: 48105,
    fuel: "Petrol",
    owner: "1st Owner",
    transmission: "auto",
    body: "SUV",
  },
  {
    id: 2,
    img: image2,
    title: "Black Car",
    desc: "A Black Car",
    price: 380000,
    distance: 18560,
    fuel: "Diesel",
    owner: "2nd Owner",
    transmission: "auto",
    body: "Coupe",
  },
  {
    id: 3,
    img: image3,
    title: "Red Car 1",
    desc: "A Red Car",
    price: 500000,
    distance: 9105,
    fuel: "Petrol",
    owner: "1st Owner",
    transmission: "auto",
    body: "sedan",
  },
  {
    id: 4,
    img: image5,
    title: "Red Car 2",
    desc: "A Red Car",
    price: 560000,
    distance: 30105,
    fuel: "Petrol",
    owner: "1st Owner",
    transmission: "auto",
    body: "Minivan",
  },
  {
    id: 5,
    img: image4,
    title: "Red Car 2",
    desc: "A Red Car",
    price: 400000,
    distance: 30105,
    fuel: "Petrol",
    owner: "1st Owner",
    transmission: "auto",
    body: "Coupe",
  },
  {
    id: 6,
    img: image1,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 670000,
    distance: 40105,
    fuel: "Gas",
    owner: "2nd Owner",
    transmission: "auto",
    body: "sedan",
  },
  {
    id: 7,
    img: image2,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 350000,
    distance: 40105,
    fuel: "Gas",
    owner: "2nd Owner",
    transmission: "auto",
    body: "Minivan",
  },
  {
    id: 8,
    img: image3,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 370000,
    distance: 40105,
    fuel: "Gas",
    owner: "2nd Owner",
    transmission: "auto",
    body: "Coupe",
  },
  {
    id: 9,
    img: image4,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 480000,
    distance: 40105,
    fuel: "Gas",
    owner: "2nd Owner",
    transmission: "auto",
    body: "sedan",
  },
  {
    id: 10,
    img: image5,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 550000,
    distance: 40105,
    fuel: "Gas",
    owner: "2nd Owner",
    transmission: "auto",
    body: "SUV",
  },
];
