import image1 from "../asset/images/slide1.jpg";
import image2 from "../asset/images/slide2.jpg";
import image3 from "../asset/images/slide3.jpg";
import image4 from "../asset/images/slide4.jpg";
import image5 from "../asset/images/slide5.jpg";

export default [
  {
    id: 1,
    img: image1,
    title: "White Car",
    desc: "A White Car",
    price: 250000,
    distance: 48105,
    year: 2019,
    fuel: "Petrol",
    owner: 1,
    transmission: "auto",
    body: "SUV",
    rating: 3.5,
    city: "Kolkata",
  },
  {
    id: 2,
    img: image2,
    title: "Black Car",
    desc: "A Black Car",
    price: 380000,
    distance: 18560,
    year: 2013,
    fuel: "Diesel",
    owner: 2,
    transmission: "auto",
    body: "Coupe",
    rating: 2.5,
    city: "Kolkata",
  },
  {
    id: 3,
    img: image3,
    title: "Red Car 1",
    desc: "A Red Car",
    price: 500000,
    distance: 9105,
    year: 2012,
    fuel: "Petrol",
    owner: 1,
    transmission: "auto",
    body: "Sedan",
    rating: 4.3,
    city: "Kolkata",
  },
  {
    id: 4,
    img: image5,
    title: "Red Car 2",
    desc: "A Red Car",
    price: 560000,
    distance: 30105,
    year: 2020,
    fuel: "Petrol",
    owner: 1,
    transmission: "auto",
    body: "Minivan",
    rating: 4.7,
    city: "Kolkata",
  },
  {
    id: 5,
    img: image4,
    title: "Red Car 2",
    desc: "A Red Car",
    price: 400000,
    distance: 30105,
    year: 2014,
    fuel: "Petrol",
    owner: 1,
    transmission: "auto",
    body: "Coupe",
    rating: 5,
    city: "Kolkata",
  },
  {
    id: 6,
    img: image1,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 670000,
    distance: 40105,
    year: 2014,
    fuel: "Gas",
    owner: 2,
    transmission: "auto",
    body: "Sedan",
    rating: 4,
    city: "Kolkata",
  },
  {
    id: 7,
    img: image2,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 350000,
    distance: 40105,
    year: 2012,
    fuel: "Gas",
    owner: 3,
    transmission: "auto",
    body: "Minivan",
    rating: 4.1,
    city: "Kolkata",
  },
  {
    id: 8,
    img: image3,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 370000,
    distance: 40105,
    year: 2019,
    fuel: "Diesel",
    owner: 2,
    transmission: "auto",
    body: "Coupe",
    rating: 3.5,
    city: "Kolkata",
  },
  {
    id: 9,
    img: image4,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 480000,
    distance: 40105,
    year: 2018,
    fuel: "Gas",
    owner: 2,
    transmission: "auto",
    body: "Sedan",
    rating: 4.5,
    city: "Kolkata",
  },
  {
    id: 10,
    img: image5,
    title: "Yellow Car",
    desc: "A Yellow Car",
    price: 550000,
    distance: 40105,
    year: 2020,
    fuel: "Gas",
    owner: 3,
    transmission: "auto",
    body: "SUV",
    rating: 3.9,
    city: "Kolkata",
  },
];
